apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: posts.com # base domain
      http:
        paths: # path order matters, from specific to general
          - path: /posts/create  # nginx does not differentiate HTTP methods
            pathType: Prefix
            backend:
              service:
                name: posts-clusterip-srv
                port:
                  number: 4000
          - path: /posts
            pathType: Prefix # for exact path
            backend:
              service:
                name: query-srv
                port:
                  number: 4002
          - path: /posts/?(.*)/comments  # does not identify params from path
            pathType: ImplementationSpecific  # for regex path
            backend:
              service:
                name: comments-srv
                port:
                  number: 4001
          - path: /?(.*)     # all other paths must be last
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
